In [1]:
import numpy as np


Hello


In [2]:
myList = [1,2,3]
type(myList)

list

In [5]:
myarray = np.array(myList)

In [6]:
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [9]:
np.arange(0,122,11)


array([  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121])

In [10]:
np.zeros(shape=(11,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [16]:
arr2 = np.random.randint(0,100,10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])